services:
  - type: web
    name: maternal-mortality-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python scripts/train_models.py
    startCommand: gunicorn app:create_app()
